### save
GET http://localhost:3000/save

### version
GET http://localhost:3000/version

### favicon
GET http://localhost:3000/favicon.ico

### start site
GET http://localhost:3000

### create
POST http://localhost:3000/create
Content-Type: application/json

{
  "who" : "Nshuti",
  "what": "Rice und   Kartoffel",
  "datum": "2023-01-06",
  "where": "Rewe Marburg",
  "status": 1
}

### create
POST http://localhost:3000/create
Content-Type: application/json

{
  "who" : "Alinee",
  "what": "Fisch",
  "datum": "2023-01-10",
  "where": "Rewe Center Gießen",
  "status": 1
}

### create
POST http://localhost:3000/create
Content-Type: application/json

{
  "who" : "Cos",
  "what": "Pommes",
  "datum": "2023-01-20",
  "where": "Gießen",
  "status": 1
}

###create
POST http://localhost:3000/create
Content-Type: application/json

{
  "who" : "Sonja",
  "what": "Brot",
  "datum": "2023-01-17",
  "where": "Gießen",
  "status": 1
}

### udate
POST http://localhost:3000/update
Content-Type: application/json

{
  "id_act": 6,
  "who" : "CosCos",
  "what": "nothing",
  "datum": "2023-01-06",
  "where": "Rewe",
  "status": 1
}

### change
POST http://localhost:3000/update
Content-Type: application/json

{
  "id_act": 11,
  "who" : "Moses",
  "what": "Talk",
  "datum": "2023-01-16",
  "where": "Rewe",
  "status": 1
}

### change
POST http://localhost:3000/read
Content-Type: application/json

{

"who" : "Moses",
"what": "Talk",
"datum": "2023-01-16",
"where": "Rewe",
"status": 1
}


### read
GET http://localhost:3000/read


### delete
POST http://localhost:3000/delete
Content-Type: application/json

{
  "id_act":  37
}
